import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import ApolloWrapper from "@/components/ApolloWrapper";
import Navigation from "@/components/Navigation/Navigation";
import "./index.scss";

const robotoCondensed = Roboto_Condensed({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Crown Clothing",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ApolloWrapper>
			<html lang="en">
				<body className={robotoCondensed.className}>
					<Navigation />
					{children}
				</body>
			</html>
		</ApolloWrapper>
	);
}
